### PR TITLE
Added bio update/Toast/prettier formatting

### PR DESCRIPTION
**Pull request by noodaj**
## Description / Changes Made
- Added Toast messages for updating bio and login fails. 
- Added function to update user settings in the profile edit. 

## How to Test
1. Install packages
2. Run app on when login, test with some random user/password
3. When logged in check update first/last name with something

## Checklist

- [x] I have added/updated relevant documentation, and I have followed the coding style guidelines.
- [x] I have added/updated tests, and I have run the test suite and all tests pass.
- [x] I have checked for any potential conflicts with other branches and fixed any merge conflicts.

## When reviewing
**There are a lot of changed files in this PR. A majority of them are not changed. This was due to the `.prettierrc` file that I added for styling if you already have prettier installed. It will help reduce the amount of changes when doing merge conflicts.**
> ### List of ignore files
>> - app.json
>> - eas.json
>> - tsconfig.json

### CODE REVIEW

**Review by mitshelle — CHANGES_REQUESTED** [review]
Great work @noodaj!

The toast alerts work well on the login page and the profile update page! 

One thing I noticed is when the password does not meet all the requirements for logging in, it shows the error message that says it should be such and such. I think we should just have no error message and show that the account isn't found. 

The popup alerts look good though! ٩(⊙‿⊙)۶

**Comment by noodaj** [comment]
> Great work @noodaj!
> 
> The toast alerts work well on the login page and the profile update page!
> 
> One thing I noticed is when the password does not meet all the requirements for logging in, it shows the error message that says it should be such and such. I think we should just have no error message and show that the account isn't found.
> 
> The popup alerts look good though! ٩(⊙‿⊙)۶

Why should we not have the error message, we haven't checked if the account did or did not exist yet. That step is to validate both the username and password before we attempt to sign in.

**Comment by mitshelle** [comment]
> > Great work @noodaj!
> > The toast alerts work well on the login page and the profile update page!
> > One thing I noticed is when the password does not meet all the requirements for logging in, it shows the error message that says it should be such and such. I think we should just have no error message and show that the account isn't found.
> > The popup alerts look good though! ٩(⊙‿⊙)۶
> 
> Why should we not have the error message, we haven't checked if the account did or did not exist yet. That step is to validate both the username and password before we attempt to sign in.

Sorry should have been more clear. That error message is good! Another message pops up when you type in the password and it doesn't have one capital letter, special character etc. It won't let you sign in if it doesn't meet the password requirements. I think that error message is a must for the registering but logging in not so much.

**Review by mitshelle — APPROVED** [review]

**Comment by mitshelle** [comment]
After discussion, we have decided that the error is ok!

**Comment by StacL** [comment]
Possible edge case:

Trying to make account with password as: `P@ssw0rd`

{"clerkError": true, "clerkTraceId": undefined, "errors": [{"code": "form_password_pwned", "longMessage": "Password has been found in an online data breach. For account safety, please use a different password.", "message": "Password has been found in an online data breach. For account safety, please use a different password.", "meta": [Object]}], "status": 422, "toString": [Function anonymous]}

image

**Review by StacL — CHANGES_REQUESTED** [review]
Hey @noodaj! Good job with the toast so far. Adding Prettier is a good idea for cleaner code too. Everything seems to work fine, except one edge case that appears when trying to create a new account. Seems like the password users put in are checked against some database of common passwords. This is a good security feature, but the toast message is wrong. Also, is there a timeout for toast notifications, or do they stay on the screen forever? Should there be a timeout, for example after a user logs in correctly?

Possible edge case:

Trying to make account with password as: `P@ssw0rd`

`{"clerkError": true, "clerkTraceId": undefined, "errors": [{"code": "form_password_pwned", "longMessage": "Password has been found in an online data breach. For account safety, please use a different password.", "message": "Password has been found in an online data breach. For account safety, please use a different password.", "meta": [Object]}], "status": 422, "toString": [Function anonymous]}`

image

**Review by StacL — APPROVED** [review]
Changes look good and bug was fixed.

**Pull request merged**
