### PR TITLE
Edit post page

### PR DESCRIPTION
**Pull request by StacL**
This is related to issue #53 

## Description / Changes Made
- Created Edit Post page for future use. Once post pages are made, then this page will be used after clicking an edit button on the post.
- Created Recipe page for future use. Once post pages are made, then this page will be used after clicking an edit button on the post.

## Screenshots (optional)
image

image

## Checklist
- [x] I have added/updated relevant documentation, and I have followed the coding style guidelines.
- [x] I have checked for any potential conflicts with other branches and fixed any merge conflicts.

### CODE REVIEW

**Review by mitshelle — APPROVED** [review]
Nice work! This is a great starting point and allows all the frontend developers to get started on this feature.

**Comment by mitshelle** [comment]
Additions look good and more applicable!

**Comment by StacL** [comment]
Thanks @mitshelle! I just added a similar looking Edit Recipe Page, which will need to make requests to the backend to retrieve previous post info!

**Review by honeepuffs — APPROVED** [review]
Great job on your components, they are very effective and great to start adding functionality. This is a great point to merge!
In the future we should have a meeting about unifying the style of each of our pages, otherwise great job!

**Pull request merged**
