### PR TITLE
Tabs For Creating a Post 

### PR DESCRIPTION
**Pull request by mitshelle**
## Description / Changes Made

- `Byte` and `Recipe` tabs for the different types of posting available 
-  Have text box for right now
- Can switch between the two and see two different messages in the text box

## How to Test

1. Navigate to Create on the homebar
2. Switch between the two tabs
3. Confirm they each show a different message for the text box

## Checklist

- [x] I have added/updated relevant documentation, and I have followed the coding style guidelines.
- [x] I have checked for any potential conflicts with other branches and fixed any merge conflicts.

### CODE REVIEW

**Review by honeepuffs — APPROVED** [review]
Hello Michelle,
I have reviewed your pr and found a great start to the create page munch. I found your decisions very intuitive and user friendly. 

As more user interface is developed we should consider a frontend meeting going over the style updating fixes so all of our things are cohesive
For example you have a light mode and others are developing with a dark mode in mind

otherwise wonderful job!

**Review by razonm — CHANGES_REQUESTED** [review]
Your changes look great! I love the different tabs. This is a great base for us to continue honing the create post design. 

However, you need to pull the updated app first. You are missing some of the latest features in your branch such as the new homepage. Once this is completed, I will approve of it.

**Comment by mitshelle** [comment]
@razonm thank you! Merged main into my branch, so it should be updated now!

**Review by razonm — APPROVED** [review]
Thank you for repulling. It looks like you have all the new components. Great work! Approved

**Pull request merged**
