### PR TITLE
Refactor Code, added default logo, added new pages

### PR DESCRIPTION
**Pull request by noodaj**
### Backend
- Added unfollowing route to get non-following posts
- Added `user_id` in the user collection for referencing throughout our application
### Explore page
- Changed `friends` page to `explore` page that encompasses `Explore` and `Friends` under one. There is a button to switch between screens.
### Profile page 
- Added slug route for `users`
- Moved the profile in the `profile` page to its own component to be used by both the `profile` page and the author slug route
- Added functionality to the `ProfileEditModal`
### Misc
- Added munch logo 
- Fixed bugs with the new backend update to likes and comments
- Added types to reflect what is returned from the back

## Portions of this code that utilized AI generation
None

## How to Test
1. Clone repo
2. Remember to add the `clerk_user_id` in the backend to your user if you haven't
3. Run through all the pages 

## Checklist

- [x] I have added/updated relevant documentation, and I have followed the coding style guidelines.
- [x] I have added/updated tests, and I have run the test suite and all tests pass.
- [x] I have checked for any potential conflicts with other branches and fixed any merge conflicts.

### CODE REVIEW

**Comment by StacL** [comment]
Wow, you have a very large PR. This added a lot of the necessary bug fixes and features that take Munch to the next level. Good job adding followers, and refactoring some of the pages was a much needed fix. Don't forget to add more detail to the description and changes made!

**Review by StacL — APPROVED** [review]
Wow, you have a very large PR. This added a lot of the necessary bug fixes and features that take Munch to the next level. Good job adding followers, and refactoring some of the pages was a much needed fix. Don't forget to add more detail to the description and changes made!

**Review by honeepuffs — CHANGES_REQUESTED** [review]
Great job on all of your changes! This is some great more things. I am getting an error when i try to open the profile page. Great job!

**Review by honeepuffs — APPROVED** [review]
Great job!

**Pull request merged**
