### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by StacL**
## Description / Changes Made
- Added bug report and feature request templates for issues. 
- Directions from: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

## How to Test
1. Create issue for bug request, check if template appears
2. Create issue for new feature, check if template appears

## Checklist
- [x] I have added/updated relevant documentation, and I have followed the coding style guidelines. N/A, not necessary.
- [x] I have added/updated tests, and I have run the test suite and all tests pass. N/A, not necessary.
- [x] I have checked for any potential conflicts with other branches and fixed any merge conflicts.

### CODE REVIEW

**Comment by mitshelle** [comment]
Nice work here @StacL! This will increase our efficiency and improve our reporting for issues. This also helps cohesiveness throughout all issues and our team.

**Review by mitshelle — APPROVED** [review]
Nice work here @StacL! This will increase our efficiency and improve our reporting for issues. This also helps cohesiveness throughout all issues and our team. I like the testing steps you added to the bug report!

**Review by rparker2003 — APPROVED** [review]
I like the new files provided. Templates for the feature request and bug report will not only improve our efficiency but will also create a consistent format for the repository!

**Comment by StacL** [comment]
Closed bc moved branch to my own forked repo and then merging to upstream main.

**Pull request closed without merging**
