### PR TITLE
Refactor Post Component

### PR DESCRIPTION
**Pull request by noodaj**
This is related to issue #58 

## Description / Changes Made
- Fixed styling that was different with my big PR being pushed while everyone was working on their individual pages
- Refactored the Post component so it renders images, texts, and buttons (no functionality, except location)
- Added type for `Byte` and `Recipes`, and `typeGuard`
- Added slug route for posts under the `(tabs)/_layout.tsx` file/ Set up slug route post file
- Refactor `(tabs)/index.tsx` to a `FlatList` (only skeleton for now, retrieval of data in next PR)
- Removed `recipes` and `comments` in tabs, moved only `comments` to the `_layout.tsx` as a stack (presented as a modal) 
- There is an issue with the dates (Will make issue soon)
## Screenshots (optional)

New Post

## How to Test
1. None

## Checklist

- [x] I have added/updated relevant documentation, and I have followed the coding style guidelines.
- [ ] I have added/updated tests, and I have run the test suite and all tests pass.
- [x] I have checked for any potential conflicts with other branches and fixed any merge conflicts.

### CODE REVIEW

**Review by honeepuffs — APPROVED** [review]
Your changes have proven very effective for the implementation of the home page. You have updated the pages very fully and effectively creating a more cohesive user interface for our page. I think the only thing to explore is a header comment at the top explaining the purpose of each document as we increase file amounts wit many different purposes.

**Review by StacL — CHANGES_REQUESTED** [review]
Great job on the recent changes @noodaj ! The code looks much cleaner now, and integrating props adds a nice touch.

In the `getDateDifference` should there be a case for seconds? Instead of saying the specific amount of seconds, we could just say "recently" or "just now", which I think is what other social media sites say. Otherwise, leaving it blank is an option too.

Additionally, I recommend moving this function to the util folder. Given its potential utility across other pages, centralizing it there would be beneficial.

**Comment by StacL** [comment]
Also, it appears we haven't yet established a standardized format for storing date strings in our backend. It would be beneficial for us to address this to ensure consistency across our platform. Specifically, we should determine the format that the createPost page will use to transmit dates is the same that this page uses to display dates. While I'm uncertain whether variations in formatting would be automatically resolved by the Date inbuilt function, clarifying this aspect would enhance our system's cohesion.

**Review by StacL — APPROVED** [review]
Good job fixing the requested changes. You code looks clean, and adding type checks is good too. We'll have to ensure other pages are using type checking and absolute paths when importing files for consistency.

**Pull request merged**
